#include <iostream>
using namespace std;

class BaseException
{
public:
    virtual void Output()
    {
        cout <<"Base" <<endl;
    }
};

class DerivedException : public BaseException
{
public:
    virtual void Output()
    {
        cout <<"Derived" <<endl;
    }
};


int main()
{
    try
    {
        throw DerivedException();
    }
    catch(BaseException &ex)
    {
        ex.Output();
    }
    catch(...)
    {
        cout <<"Uncnown" <<endl;
    }

    return 0;
}

